export const gradientGeneratorContent = {
  toolName: 'CSS Gradient Generator',
  introduction: (
    <>
      <p className="mb-4">
        The ColorForge AI CSS Gradient Generator is the ultimate visual tool for creating complex, breathtaking gradients. In modern web design, gradients are no longer just simple linear fades between two colors; they are complex mesh structures, intricate radial bursts, and sharp conic sweeps that add depth, texture, and glassmorphic realism to user interfaces.
      </p>
      <p className="mb-4">
        Our gradient generator empowers designers and developers to construct these intricate visual elements without having to memorize complex CSS syntax. Whether you need a subtle background for a hero section or a vibrant, attention-grabbing CTA button, this tool provides instant visual feedback and mathematically perfect CSS and Tailwind code generation.
      </p>
      <p>
        By utilizing a precision visual editor, you can add up to five separate color stops, drag them to adjust their positions, and seamlessly switch between Linear, Radial, and Conic rendering engines. It is designed to bridge the gap between creative exploration and production-ready code.
      </p>
    </>
  ),
  howToUse: [
    {
      step: 'Choose Your Gradient Type',
      desc: 'Start by selecting the base rendering engine: Linear (a straight-line transition), Radial (a circular transition expanding from the center), or Conic (a sweep around a central point, great for pie charts or metallic effects).',
    },
    {
      step: 'Adjust the Angle',
      desc: 'For Linear and Conic gradients, use the angle slider to rotate the entire gradient. This is crucial for creating dynamic, diagonal lighting effects.',
    },
    {
      step: 'Manage Color Stops',
      desc: 'Add up to 5 distinct color stops. Click on any stop to activate it, then use the color picker below to adjust its hue. Drag the slider next to the stop to change its percentage position along the gradient.',
    },
    {
      step: 'Export Your Code',
      desc: 'Once your gradient looks perfect in the live preview, head to the Export Options panel. You can instantly copy the raw CSS background property or a Tailwind CSS arbitrary value string to drop straight into your markup.',
    },
  ],
  examples: [
    {
      title: 'Hero Section Backgrounds',
      desc: 'Create a massive, subtle radial gradient to sit behind your main headline. Use very dark, unsaturated colors (e.g., #0f172a to #1e293b) to create a premium "Dark Mode" aesthetic that draws the eye toward the center text.',
    },
    {
      title: 'Vibrant Call-to-Action Buttons',
      desc: 'Use a tight linear gradient (e.g., #ff0844 to #ffb199) on your primary buttons. This creates a "clickable", elevated appearance that converts significantly better than flat colors.',
    },
    {
      title: 'Glassmorphism Overlays',
      desc: 'Create a gradient transitioning from white with 40% opacity to white with 10% opacity. Overlay this on top of images to create a frosted glass effect that makes overlaying text highly readable.',
    },
    {
      title: 'Metallic UI Elements',
      desc: 'Use a Conic gradient with multiple repeating stops of gray, silver, and white to create a realistic metallic sheen, perfect for high-end product renders or specialized UI toggles.',
    },
  ],
  benefits: [
    'Live visual preview eliminates the frustrating trial-and-error of manually typing CSS percentages.',
    'Instantly generates complex syntax like conic-gradient(), which is notoriously difficult to write by hand.',
    'Provides direct Tailwind CSS support via arbitrary values (e.g., bg-[linear-gradient(...)]).',
    'Curated Gradient Library allows you to bootstrap your design with proven, beautiful presets.',
  ],
  mistakes: [
    'Using highly saturated, contrasting colors (like pure red to pure green) which creates a "muddy", ugly transition in the middle.',
    'Forgetting that gradients can be used on text! (Using background-clip: text).',
    'Adding too many color stops too close together, resulting in harsh lines instead of smooth fades.',
  ],
  proTips: [
    'To avoid "muddy" mid-tones when transitioning between two contrasting colors, add a third color stop exactly in the middle with a carefully chosen intermediate hue.',
    'You can create hard stripes instead of smooth fades by setting two consecutive color stops to the exact same percentage.',
    'Combine a subtle CSS gradient with a noise texture overlay to create an incredibly realistic, tactile "grainy" gradient effect.',
  ],
  faqs: [
    {
      question: 'What is a CSS Gradient?',
      answer: 'A CSS gradient is a smooth transition between two or more specified colors. Instead of using image files to create these effects, CSS gradients are generated by the browser natively, making them infinitely scalable, bandwidth-free, and highly performant.',
    },
    {
      question: 'What is the difference between Linear, Radial, and Conic?',
      answer: 'Linear gradients transition colors along a straight line (up, down, diagonal). Radial gradients transition colors outward from a central point in a circular or elliptical shape. Conic gradients transition colors rotated around a central point, like a radar sweep.',
    },
    {
      question: 'Does Tailwind CSS support complex gradients?',
      answer: 'Yes! While Tailwind has utility classes for simple two-color linear gradients (e.g., bg-gradient-to-r from-red-500 to-blue-500), our generator provides Tailwind "arbitrary values" which allow you to use complex radial and conic gradients with multiple stops directly in your class attributes.',
    },
    {
      question: 'How do I apply a gradient to text?',
      answer: 'To apply the CSS generated by our tool to text, apply the background gradient to your text element, and then add two additional CSS properties: `background-clip: text;` and `-webkit-text-fill-color: transparent;`.',
    },
    {
      question: 'Are CSS gradients bad for performance?',
      answer: 'No, native CSS gradients are hardware-accelerated by modern browsers and are vastly superior to using background images in terms of performance and load times.',
    },
  ],
  relatedTools: [
    { name: 'Color Picker', href: '/color-picker' },
    { name: 'Tailwind Generator', href: '/tailwind-color-generator' },
    { name: 'Palette Generator', href: '/color-palette-generator' },
  ],
};
