import React from 'react';
import { Droplet, Sparkles, Copy, MonitorPlay } from 'lucide-react';

export const gradientBackgroundsContent = {
  title: "1000+ CSS Gradient Backgrounds",
  description: "Stop spending hours trying to find the perfect CSS gradient. Browse our curated collection of over 1000 beautiful, hand-crafted gradients ready to be used in your next project.",
  features: [
    {
      title: "Curated Collection",
      description: "Every gradient is hand-picked to ensure maximum aesthetic appeal and modern design trends.",
      icon: <Droplet className="w-6 h-6 text-primary" />
    },
    {
      title: "Instant Copy",
      description: "One click copies the pure CSS code. No external libraries or images required.",
      icon: <Copy className="w-6 h-6 text-primary" />
    },
    {
      title: "Tailwind Ready",
      description: "Toggle between standard CSS and Tailwind utility classes for seamless integration into modern stacks.",
      icon: <Sparkles className="w-6 h-6 text-primary" />
    },
    {
      title: "Fullscreen Preview",
      description: "See exactly how the gradient will look across a large viewport before copying the code.",
      icon: <MonitorPlay className="w-6 h-6 text-primary" />
    }
  ],
  faqs: [
    {
      question: "Are these gradients free to use?",
      answer: "Absolutely! All gradients in this collection are completely free and open-source. You can use them in personal or commercial projects without attribution."
    },
    {
      question: "Why use CSS gradients instead of images?",
      answer: "CSS gradients are generated by the browser, meaning they take 0 bytes of network request overhead, load instantly, and perfectly scale to any resolution without pixelation."
    },
    {
      question: "Can I edit the gradients?",
      answer: "Yes, you can copy the CSS and tweak the color stops or angles directly in your code, or take the colors to our Custom Gradient Generator for a visual builder."
    }
  ]
};
